services:
  posrgres:
    image: postgres:15
    container_name: go-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


